### ISSUE TITLE
Calendar Widget Not Pulling 2018 Dates/Data

### ISSUE THREAD

**Issue by huebschie** [OvRcode/ovrride#228] opened 2017-09-15 17:13 UTC
The Calendar is getting hung up if you try to scroll past December 2017. Can we fix so customers can browse upcoming trips by date?

**Comment by barnardm** [comment] 2017-09-18 11:24
Absolutely fixable, I'll try to look at this tonight. I'm not 100% sure where the issue is at the moment the error being thrown is very generic

**Comment by barnardm** [comment] 2017-09-29 14:15
Starting to dig into this, mostly leaving this here so I remember where I'm at when I come back to this later. The live version of the calendar is hitting a memory limit in hhvm. I tried upping the memory limit in development which squashed the error but then crashed the hhvm process, failed over to php-7 and then crashed php. I'm going to have to go through the calendar functions and see if I can pin point where the error is occurring, no new errors where shown in development environment.

**Comment by barnardm** [comment] 2017-10-01 13:05
I've got a temporary fix for this online now. The only issue left is that trips that start in one month and end in another don't show on the second month. Ex: Alps trip is 01/26 - 02/03 won't show on feb 1-3 but will show to the end of January

**Comment by barnardm** [comment] 2017-11-20 19:08
This has been resolved with the last calendar update. Start/end in different months will now render properly on the calendar.

**Closed by barnardm** 2017-11-20 19:08 UTC
